
- name: Configure repos and update package cache (only once per host)
  block:
    - name: Enable sources repository
      become: yes
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
      with_items:
        - { repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse' }
        - { repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse' }
        - { repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse' }
        - { repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-backports main restricted universe multiverse' }
        - { repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-proposed main restricted universe multiverse' }
        - { repo: 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse' }
        - { repo: 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse' }
        - { repo: 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse' }
        - { repo: 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-backports main restricted universe multiverse' }
        - { repo: 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-proposed main restricted universe multiverse' }

    - name: Update package cache
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: yes
      apt:
        upgrade: dist

    - name: Add amnezia repository ppa:amnezia/ppa
      become: yes
      apt_repository:
        repo: 'ppa:amnezia/ppa'
        state: present

- name: Install python3 and python3-pip
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
